name: Ritualism
description: a minimalistic app designed to help you track habits, rituals, and personal growth. Seamlessly monitor your daily routines and set goals with an intuitive interface that keeps you focused on what matters most. 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  table_calendar: ^3.0.0
  flutter_heatmap_calendar: ^1.0.0
  shared_preferences: ^2.0.13
  rename: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true